# Generated by Django 3.1 on 2020-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('tittle', models.CharField(default=None, max_length=255, null=True)),
                ('image_url', models.URLField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('extra_feild', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
